Repository kiegroup/optaplanner, pull requests merged in 2023-05, with the labels that each got.

#2804 Set Freemarker compatibility to 2.3.31
  optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/config/PlannerBenchmarkConfig.java
  optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/report/BenchmarkReport.java
Labels: backport-8.38.x

#2812 Correct post-release job for Stream 8
  .ci/jenkins/project/Jenkinsfile.post-release
Labels: backport-8.38.x, backport-9.38.x

#2838 [RHPAM-4700] snakeyaml from 1.32 to 2.0
  optaplanner-quickstarts/spring-boot-school-timetabling/pom.xml
Labels: backport-7.67.x

#2848 Include optaplanner-website in prod repos to keep seed job working
  .ci/jenkins/config/branch.yaml
Labels: backport-8.38.x-prod
