Repository kiegroup/optaplanner, pull requests merged in 2023-02, with the labels that each got.

#2561 Fix nightly pipeline
  .ci/jenkins/project/Jenkinsfile.nightly
  build/8-to-9-migration/migrate.sh
Labels: backport-9.x

#2589 Deploy pipeline: Stage artifacts need jdk11
  .ci/jenkins/Jenkinsfile.deploy
Labels: backport-8.34.x, backport-9.34.x

#2597 DSL: Update GH token credentials id
  .ci/jenkins/config/branch.yaml
Labels: backport-1.33.x, backport-8.33.x, backport-9.x, backport-8.34.x, backport-9.34.x, backport-1.13.x

#2610 DSL Config: Update Git credentials
  .ci/jenkins/config/branch.yaml
Labels: backport-8.33.x, backport-8.34.x

#2615 DSL branch Config: Revert quarkus credentials
  .ci/jenkins/config/branch.yaml
Labels: backport-8.33.x, backport-8.34.x, backport-9.34.x
